version: "3.7"

services:
  postgres:
    container_name: usufruct_postgres
    image: postgres:14
    ports:
      - 5432:5432
    environment:
      - "POSTGRES_PASSWORD=local"
      - "POSTGRES_USER=local"
      - "POSTGRES_DB=usufruct"
  adminer:
    container_name: usufruct_adminer
    image: wodby/adminer:4.8
    ports:
      - 9000:9000
    environment:
      - "ADMINER_DEFAULT_DB_DRIVER=pgsql"
      - "ADMINER_DEFAULT_DB_HOST=postgres"
      - "ADMINER_DEFAULT_DB_NAME=usufruct"
    depends_on:
      - postgres

  maildev:
    container_name: usufruct_maildev
    image: maildev/maildev
    ports:
      - "1080:80"
      - "1025:25"

  redis:
    container_name: usufruct_redis
    image: redis:6.2.6
    ports:
      - 6379:6379

  redis_commander:
    container_name: usufruct_redis_commander
    image: rediscommander/redis-commander
    environment:
      - "REDIS_HOST=redis"
      - "REDIS_PORT=6379"
    ports:
      - "8081:8081"
    depends_on:
      - redis

  s3:
    container_name: usufruct_s3
    image: lphoward/fake-s3
    ports:
      - "4569:4569"
