kind: pipeline
type: kubernetes
name: usufruct server

steps:
  - name: setup
    image: node:16
    commands:
      - "yarn"
  
  - name: generate openapi-spec
    image: node:16
    commands:
      - "yarn generate:openapi-spec"

services:
- name: postgres
  image: postgres:14
  environment:
    POSTGRES_PASSWORD: "local"
    POSTGRES_USER: "local"
    POSTGRES_DB: "usufruct"
- name: redis
  image: redis:6.2.6