kind: pipeline
type: kubernetes
name: usufruct server

steps:
  - name: setup
    image: node:16
    commands:
      - "yarn"
  
  - name: generate sdk
    image: node:16
    when:
      ref:
      - refs/tags/server-*.*.* #When there is a tag like server-0.0.1 then build the sdk and publish it at version 0.0.1
    commands:
      - "export tag=$DRONE_TAG && echo $tag"
      - 'export npmVersion=$(echo $tag | sed -e s/^server-//) && echo $npmVersion'
      - "yarn generate:sdk"

services:
- name: postgres
  image: postgres:14
  environment:
    POSTGRES_PASSWORD: "local"
    POSTGRES_USER: "local"
    POSTGRES_DB: "usufruct"
- name: redis
  image: redis:6.2.6